workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      ANDROID_SIGNING_KEY:
        secure: YOUR_SECURE_ANDROID_SIGNING_KEY
      KEYSTORE_PASSWORD:
        secure: YOUR_SECURE_KEYSTORE_PASSWORD
      KEY_ALIAS:
        secure: YOUR_SECURE_KEY_ALIAS
      KEY_PASSWORD:
        secure: YOUR_SECURE_KEY_PASSWORD
    scripts:
      - name: Flutter Build
        script: |
          flutter build apk --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk